#!/usr/bin/env bash
echo "Syncing bucket: $1"
set -e

if [ -z "$1" ]; then
    echo "There need to be a bucket name"
    exit 1
fi
BUCKET_NAME=$1
aws s3 rm s3://$BUCKET_NAME --recursive
# aws s3api delete-objects --bucket $BUCKET_NAME --delete "$(aws s3api list-objects --bucket $BUCKET_NAME --query 'Contents[].Key' --output text)"    